export const GET_UNITS_START="GET_UNITS_START";
export const GET_UNITS_SUCCESS="GET_UNITS_SUCCESS";
export const GET_UNITS_FAIL="GET_UNITS_FAIL";

export const CREATE_UNIT_START="CREATE_UNIT_START";
export const CREATE_UNIT_SUCCESS="CREATE_UNIT_SUCCESS";
export const CREATE_UNIT_FAIL="CREATE_UNIT_FAIL";

export const UPDATE_UNIT_START="UPDATE_UNIT_START";
export const UPDATE_UNIT_SUCCESS="UPDATE_UNIT_SUCCESS";
export const UPDATE_UNIT_FAIL="UPDATE_UNIT_FAIL";

export const DELETE_UNIT_START="DELETE_UNIT_START";
export const DELETE_UNIT_SUCCESS="DELETE_UNIT_SUCCESS";
export const DELETE_UNIT_FAIL="DELETE_UNIT_FAIL";