export const CREATE_PURCHASE = "CREATE_PURCHASE";

export const UPDATE_PURCHASE = "UPDATE_PURCHASE";

export const DELETE_PURCHASE = "DELETE_PURCHASE";

export const GET_PURCHASES = "GET_PURCHASES";

export const GET_PURCHASE_BY_ID="GET_PURCHASE_BY_ID";