
export const GET_CATEGORIES_SUCCESS="GET_CATEGORIES_SUCCESS";

export const CREATE_CATEGORY_SUCCESS="CREATE_CATEGORY_SUCCESS";

export const UPDATE_CATEGORY_SUCCESS="UPDATE_CATEGORY_SUCCESS";

export const DELETE_CATEGORY_SUCCESS="DELETE_CATEGORY_SUCCESS";
