export const LOGIN_START="LOGIN_START";
export const LOGIN_SUCCESS="LOGIN_SUCCESS";
export const LOGIN_FAIL="LOGIN_FAIL";
export const LOG_OUT="LOG_OUT";
export const SET_REDIRECT_PATH="SET_REDIRECT_PATH";